global:
  imagePullPolicy: IfNotPresent
  ###vault:
  ###  host: ip
  ###  name: vault
  ###  vaultToken: someToken


frontend:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  containerPort: 80
  ingress:
    host: front-ypenjoyer333.2sem.students-projects.ru
    path: /
    pathType: Prefix
    tls:
      secretName: 2sem-students-projects-wildcard-secret
  image:
    name: ypenjoyer333/sausage-frontend
    tag: latest
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    POSTGRES_URI: jdbc:postgresql://postgresql:5432/sausage-store
    POSTGRES_USER: store
    POSTGRES_PASSWORD: storepassword
    REPORT_PATH: /logs/reports
    LOG_PATH: /logs
    MONGODB_URI: mongodb://example:changeme@mongodb:27017/reports
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  image:
    name: ypenjoyer333/sausage-backend
    tag: latest
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  containerPort: 8080
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  vpa:
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: backend
          controlledResources:
            - cpu
            - memory
          controlledValues: RequestsAndLimits
          minAllowed:
            cpu: "200m"
            memory: "256Mi"
          maxAllowed:
            cpu: "500m"
            memory: "512Mi"

backend-report:
  revisionHistoryLimit: 15
  replicas: 1
  env:
    PORT: 8080
    MONGODB_URI: mongodb://example:changeme@mongodb:27017/reports
  strategy:
    type: Recreate
  service:
    port: 8080
  image:
    name: ypenjoyer333/sausage-backend-report
    tag: latest
  resources:
    requests:
      cpu: "75m"
      memory: "96Mi"
    limits:
      cpu: "150m"
      memory: "192Mi"
  containerPort: 8080
  livenessProbe:
    httpGet:
      path: /api/v1/health
      port: 8080
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  hpa:
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 50
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 70

infra:
  postgresql:
    env:
      POSTGRES_USER: store
      POSTGRES_PASSWORD: storepassword
      POSTGRES_DB: sausage-store
    servicePort: 5432
    containerPort: 5432
    storage: 1Gi
    resources:
      requests:
        cpu: "150m"
        memory: "192Mi"
      limits:
        cpu: "400m"
        memory: "384Mi"
  mongodb:
    env:
      MONGO_INITDB_ROOT_USERNAME: root # todo move to secrets
      MONGO_INITDB_ROOT_PASSWORD: rootchangeme # todo move to secrets
      MONGO_USER: example
      MONGO_PASSWORD: changeme
      MONGO_DATABASE: reports
    servicePort: 27017
    containerPort: 27017
    storage: 1Gi
    resources:
      requests:
        cpu: "75m"
        memory: "96Mi"
      limits:
        cpu: "150m"
        memory: "192Mi"
    initJobResources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "150m"
        memory: "384Mi"
