---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
type: Opaque
stringData:
  postgres_uri: {{ .Values.env.POSTGRES_URI | quote }}
  postgres_user: {{ .Values.env.POSTGRES_USER | quote }}
  postgres_password: {{ .Values.env.POSTGRES_PASSWORD | quote }}
  mongodb_uri: {{ .Values.env.MONGODB_URI | quote }}
